---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: demo
  annotations:
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: mongodb
  chart:
    git: https://github.com/helm/charts.git
    ref: master
    path: stable/mongodb
  values:
    image:
      repository: bitnami/mongodb
      tag: 4.0.6
    usePassword: false
    persistence:
      enabled: false
    securityContext:
      enabled: true
      fsGroup: 0
      runAsUser: 0
